package org.mhh.Filters;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;

public class CsrfCookieFilter extends OncePerRequestFilter {
    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
        //get token from request
        CsrfToken csrfToken= (CsrfToken) request.getAttribute(CsrfToken.class.getName());
        //check if its not null means that my sever generate csrf token
        if(csrfToken.getHeaderName()!=null){
            //set the csrf token that generated by server to response
            response.setDateHeader(csrfToken.getHeaderName(), Long.parseLong(csrfToken.getToken()));
        }
        filterChain.doFilter(request,response);
    }
}
